Update MainCLI.java
MCPHackers/RetroMCP-Java pull request #25
Opened 2022-06-29 22:33 UTC by vlOd2

Fix https://github.com/MCPHackers/RetroMCP-Java/issues/24

2022-08-12 21:01 UTC, ThexXTURBOXx requested changes

2022-08-12 21:01 UTC, ThexXTURBOXx commented on src/main/java/org/mcphackers/mcp/main/MainCLI.java
> +			    		System.loadLibrary("c");
Why is this needed in the first place?

2022-08-12 21:01 UTC, ThexXTURBOXx commented on src/main/java/org/mcphackers/mcp/main/MainCLI.java
> +				if (!currOs.contains("Windows")) {
Wrong indentation

2022-08-12 21:01 UTC, ThexXTURBOXx commented on src/main/java/org/mcphackers/mcp/main/MainCLI.java
> +        	if (System.console() != null && System.getProperty("doNotUseConsole") == null) {
Wrong indentation

2022-08-12 21:02 UTC, ThexXTURBOXx commented
Sorry, just noticed that this is marked as will-not-fix

2022-08-14 15:27 UTC, Lassebq commented
Yeah, I forgot to close pull request to that issue, doing that now

2022-08-14 15:27 UTC, closed without merging